# Generated by Django 3.1.7 on 2021-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210407_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='title',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='published_year',
            field=models.IntegerField(default=False),
        ),
    ]
