# Generated by Django 3.1.7 on 2021-04-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210408_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='type',
            new_name='book_title',
        ),
    ]
