# Generated by Django 3.1.7 on 2021-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210408_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
