# Generated by Django 3.1.7 on 2021-04-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookmodel_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='book_title',
            new_name='title',
        ),
    ]
